config/routes.rb
Rails.application.routes.draw do
  resources :benches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bench.rb
class Bench < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/benches_controller.rb
class BenchesController < ApplicationController
  before_action :set_bench, only: %i[ show edit update destroy ]

  # GET /benches or /benches.json
  def index
    @benches = Bench.all
  end

  # GET /benches/1 or /benches/1.json
  def show
  end

  # GET /benches/new
  def new
    @bench = Bench.new
  end

  # GET /benches/1/edit
  def edit
  end

  # POST /benches or /benches.json
  def create
    @bench = Bench.new(bench_params)

    respond_to do |format|
      if @bench.save
        format.html { redirect_to bench_url(@bench), notice: "Bench was successfully created." }
        format.json { render :show, status: :created, location: @bench }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bench.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /benches/1 or /benches/1.json
  def update
    respond_to do |format|
      if @bench.update(bench_params)
        format.html { redirect_to bench_url(@bench), notice: "Bench was successfully updated." }
        format.json { render :show, status: :ok, location: @bench }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bench.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /benches/1 or /benches/1.json
  def destroy
    @bench.destroy

    respond_to do |format|
      format.html { redirect_to benches_url, notice: "Bench was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bench
      @bench = Bench.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bench_params
      params.require(:bench).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/benches_helper.rb
module BenchesHelper
end

app/views/benches/_bench.html.erb
<div id="<%= dom_id bench %>">
  <p>
    <strong>Description:</strong>
    <%= bench.description %>
  </p>

</div>

app/views/benches/_form.html.erb
<%= form_with(model: bench) do |form| %>
  <% if bench.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bench.errors.count, "error") %> prohibited this bench from being saved:</h2>

      <ul>
        <% bench.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/benches/edit.html.erb
<h1>Editing bench</h1>

<%= render "form", bench: @bench %>

<br>

<div>
  <%= link_to "Show this bench", @bench %> |
  <%= link_to "Back to benches", benches_path %>
</div>

app/views/benches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Benches</h1>

<div id="benches">
  <% @benches.each do |bench| %>
    <%= render bench %>
    <p>
      <%= link_to "Show this bench", bench %>
    </p>
  <% end %>
</div>

<%= link_to "New bench", new_bench_path %>

app/views/benches/new.html.erb
<h1>New bench</h1>

<%= render "form", bench: @bench %>

<br>

<div>
  <%= link_to "Back to benches", benches_path %>
</div>

app/views/benches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bench %>

<div>
  <%= link_to "Edit this bench", edit_bench_path(@bench) %> |
  <%= link_to "Back to benches", benches_path %>

  <%= button_to "Destroy this bench", @bench, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Benches</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>